version: '3'
services:

#  other-services:
#    details

  servers-nginx:
    container_name: servers-nginx
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./servers_nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
#    depends_on:
#      - ...
#      - ...
#      - ...
#      - ...

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw

